kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: weboperator
subjects:
- kind: ServiceAccount
  name: weboperator
roleRef:
  kind: Role
  name: weboperator
  apiGroup: rbac.authorization.k8s.io
